#include<stdio.h>
int main () {
	int A[5], B[5], C[5], a; //Declarando meus vetores e inteiras
	for (a = 0; a < 5; a++) { //Loop para ler os números
		printf ("Digite seu numero da matriz A:\n"); //Sempre repita...
		scanf ("%i", &A[a]);}  //Sempre passe esse valor para a variável
	for (a = 0; a < 5; a++) { //Loop para ler os números
		printf ("Digite seu numero da matriz B:\n"); //Sempre repita...
		scanf ("%i", &B[a]);}  //Sempre passe esse valor para a variável
	for (a = 0; a < 5; a++) { //Loop para ordenação
		for (int b = a + 1; b < 5; b++) { //Loop...
			if (A[a] > A[b]) { //Se A[a] menor que A[b], segue
				int c = A[a]; //Troca de valores...
				A[a] = A[b]; //Trocando valores
				A[b] = c;}}} //Trocando mais valores...
	for (a = 0; a < 5; a++) { //Loop para ordenação
		for (int b = a + 1; b < 5; b++) { //Loop...
			if (B[a] > B[b]) { //Se B[a] menor que B[b], segue
				int c = B[a]; //Troca de valores...
				B[a] = B[b]; //Trocando valores
				B[b] = c;}}} //Trocando mais valores...
	for (a = 0; a < 5; a++) { //Loop de repetição...
		C[a] = A[a] + B[a];} //Soma...
	printf ("A soma do seus numeros em ordem crescente:\n"); //Mostre essa mensagem para o usuário.
	for (a = 0; a < 5; a++) { //Loop para exibição
		printf ("%i\n", C[a]);} //mostre a variável para o usuário
	return 0;} //Fim do programa... :V
