#include<stdio.h>
int main () {
	int A[3], B[3], a; //Declarando minhas variáveis inteiras
	for (a = 0; a < 3; a++) { //Loop de repetição...
		printf ("Digite seu numero:\n"); //Sempre repita...
		scanf ("%i", &A[a]);}  //Sempre passe esse valor para a variável
	for (a = 0; a < 3; a++) { //Loop do for...
		for (int b = a + 1; b < 3; b++) { //Código de laço... Loop
			if (A[a] < A[b]) { //Se A[a] menor que A[b], segue
				int c = A[a]; //Passando valor de A[a] para uma nova variável c.
				A[a] = A[b]; //Passando valores...
				A[b] = c;}}} //Passando mais valores...
	for (a = 0; a < 3; a++) { //Laço do for...
		B[a] = A[a]*A[a]*A[a];} //O vetor B é igual ao cubo do Vetor A
	printf ("Seus numeros ao cubo, em ordem decrescente:\n"); //Mostre essa mensagem para o usuário.
	for (a = 0; a < 3; a++) { //Loop...
		printf ("%i\n", B[a]);} //mostre a variável para o usuário
	return 0;} //Fim do programa... :>
