#include<stdio.h>
int main () {
	int A[2], B[2], a; //Declarando minhas variáveis inteiras
	for (a = 0; a < 2; a++) { //Loop de repetição...
		printf ("Digite seu numero:\n"); //Sempre repita...
		scanf ("%i", &A[a]);}  //Sempre passe esse valor para a variável
	for (a = 0; a < 3; a++) { //Laço do for...
		B[a] = A[a] + 2;} //O vetor B é igual ao Vetor A + 2
	for (a = 0; a < 2; a++) { //Loop do for...
		for (int b = a + 1; b < 2; b++) { //Código de laço... Loop
			if (B[a] > B[b]) { //Se A[a] menor que A[b], segue
				int c = B[a]; //Passando valor de A[a] para uma nova variável c.
				B[a] = B[b]; //Passando valores...
				B[b] = c;}}} //Passando mais valores...
	printf ("Seus numeros mais 2, em ordem crescente:\n"); //Mostre essa mensagem para o usuário.
	for (a = 0; a < 2; a++) { //Loop...
		printf ("%i\n", B[a]);} //mostre a variável para o usuário
	return 0;} //Fim do programa... :!
